//! The virtual screen: a vt100 model with truthful replies to terminal queries, a
//! revision that moves only on visible change, and style runs for snapshots.

use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};

use mira_protocol::ids::ScreenRevision;
use mira_protocol::ipc::{TerminalColor, TerminalModifier, TerminalStyleRun};

/// Bound on terminal query replies generated by one output chunk.
const MAX_REPLY_BYTES: usize = 4 * 1024;

/// Answers the few terminal queries a virtual terminal can answer truthfully: cursor
/// position, device status, and primary device attributes. Everything else is ignored.
#[derive(Default)]
pub(super) struct Replies {
    pub(super) out: Vec<u8>,
}

impl vt100::Callbacks for Replies {
    fn unhandled_csi(
        &mut self,
        screen: &mut vt100::Screen,
        i1: Option<u8>,
        i2: Option<u8>,
        params: &[&[u16]],
        c: char,
    ) {
        if i1.is_some() || i2.is_some() || self.out.len() >= MAX_REPLY_BYTES {
            return;
        }
        let first = params.first().and_then(|p| p.first()).copied();
        match (c, first) {
            ('n', Some(6)) => {
                let (row, col) = screen.cursor_position();
                self.out
                    .extend(format!("\x1b[{};{}R", row + 1, col + 1).into_bytes());
            }
            ('n', Some(5)) => self.out.extend(b"\x1b[0n"),
            ('c', None | Some(0)) => self.out.extend(b"\x1b[?1;2c"),
            _ => {}
        }
    }
}

pub(super) struct Screen {
    pub(super) parser: vt100::Parser<Replies>,
    pub(super) revision: ScreenRevision,
    pub(super) fingerprint: u64,
    pub(super) exited: bool,
}

impl Screen {
    pub(super) fn new(rows: u16, cols: u16) -> Self {
        let parser = vt100::Parser::new_with_callbacks(rows, cols, 0, Replies::default());
        let mut s = Self {
            parser,
            revision: ScreenRevision::ZERO,
            fingerprint: 0,
            exited: false,
        };
        s.fingerprint = s.fingerprint_now();
        s
    }

    fn fingerprint_now(&self) -> u64 {
        let mut h = DefaultHasher::new();
        self.parser.screen().state_formatted().hash(&mut h);
        self.parser.screen().alternate_screen().hash(&mut h);
        self.parser.screen().size().hash(&mut h);
        h.finish()
    }

    pub(super) fn bump(&mut self) {
        if let Some(n) = self.revision.next() {
            self.revision = n;
        }
    }

    /// Bumps the revision only when the visible state really changed.
    pub(super) fn refresh(&mut self) {
        let f = self.fingerprint_now();
        if f != self.fingerprint {
            self.fingerprint = f;
            self.bump();
        }
    }
}

fn color(c: vt100::Color) -> TerminalColor {
    match c {
        vt100::Color::Default => TerminalColor::Default,
        vt100::Color::Idx(index) => TerminalColor::Indexed { index },
        vt100::Color::Rgb(r, g, b) => TerminalColor::Rgb { r, g, b },
    }
}

type StyleKey = (TerminalColor, TerminalColor, Vec<TerminalModifier>);

fn cell_style(cell: &vt100::Cell) -> StyleKey {
    let mut m = Vec::new();
    for (on, modifier) in [
        (cell.bold(), TerminalModifier::Bold),
        (cell.dim(), TerminalModifier::Dim),
        (cell.italic(), TerminalModifier::Italic),
        (cell.underline(), TerminalModifier::Underline),
        (cell.inverse(), TerminalModifier::Reverse),
    ] {
        if on {
            m.push(modifier);
        }
    }
    (color(cell.fgcolor()), color(cell.bgcolor()), m)
}

fn is_default(k: &StyleKey) -> bool {
    k.0 == TerminalColor::Default && k.1 == TerminalColor::Default && k.2.is_empty()
}

/// Non-default style runs of one row; runs never cross `cols`.
pub(super) fn style_row(screen: &vt100::Screen, row: u16, cols: u16) -> Vec<TerminalStyleRun> {
    let mut runs = Vec::new();
    let mut current: Option<(u16, u16, StyleKey)> = None;
    for col in 0..cols {
        let key = screen.cell(row, col).map_or(
            (TerminalColor::Default, TerminalColor::Default, vec![]),
            cell_style,
        );
        match &mut current {
            Some((_, count, k)) if *k == key => *count += 1,
            _ => {
                if let Some((start, count, k)) = current.take()
                    && !is_default(&k)
                {
                    runs.push(TerminalStyleRun {
                        start_cell: start,
                        cell_count: count,
                        fg: k.0,
                        bg: k.1,
                        modifiers: k.2,
                    });
                }
                current = Some((col, 1, key));
            }
        }
    }
    if let Some((start, count, k)) = current
        && !is_default(&k)
    {
        runs.push(TerminalStyleRun {
            start_cell: start,
            cell_count: count,
            fg: k.0,
            bg: k.1,
            modifiers: k.2,
        });
    }
    runs
}

/// Keeps only printable text: the parser already consumed control sequences, but a cell
/// may still carry stray control characters from malformed input.
pub(super) fn printable(s: String) -> String {
    if s.chars().any(char::is_control) {
        s.chars().filter(|c| !c.is_control()).collect()
    } else {
        s
    }
}
